VERILOG_SOURCES = ../hdl/simple_dual_port_ram_two_clocks.v

export COCOTB_REDUCED_LOG_FMT = true

TOPLEVEL = simple_dual_port_ram_two_clocks
MODULE = simple_dual_port_ram_two_clocks_tb

include $(COCOTB)/makefiles/Makefile.inc
include $(COCOTB)/makefiles/Makefile.sim